---
name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go build .
        env:
          CGO_ENABLED: 0
      - uses: actions/upload-artifact@v4
        with:
          name: executable
          path: |
            ndn-prefix-reach
