---
name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18"
      - uses: actions/checkout@v3
      - run: go build .
        env:
          CGO_ENABLED: 0
      - uses: actions/upload-artifact@v3
        with:
          name: executable
          path: |
            ndn-prefix-reach
